[🇰🇷Korean Ver.] iOS-Clean-Architecture-MVVM
kudoleh/iOS-Clean-Architecture-MVVM pull request #14
Opened 2021-04-11 14:17 UTC by yeahsilver

2021-04-11 14:19 UTC, yeahsilver commented
Korean ver is included in KOREAN.md

2021-11-18 08:59 UTC, Limwin94 requested changes
안녕하세요~! 먼저 좋은 레퍼런스 번역 감사드립니다.🙏🏻

맞춤법, 해석에 대해 의견을 달아보았습니다. 확인해주시고 도움이 되었으면 좋겠습니다.
감사합니다.

2021-11-18 08:59 UTC, Limwin94 commented on README.md
> +## 필수 요소
`Requirements`가 필수 요소로 해석되기 보다는 요구 사항에 가까울 것 같습니다.

Firebase 한국어 버전을 참고 했습니다. [참고 링크](https://firebase.google.com/docs/ios/setup?hl=ko)

2021-11-18 08:59 UTC, Limwin94 commented on README.md
> +영화를 찾기 위해선 서치바에 이름을 적고 찾기 버튼을 누른다.
`영화 이름`이 명확해 보입니다~!

2021-11-18 08:59 UTC, Limwin94 commented on README.md
> +여기서는  영화 요청과 poster image 요청의 두개의 네트워크가 호출된다. 성공된 모든 검색 쿼리는 영구적으로 보존된다.
`두 개의`로 교정 부탁드립니다.

2021-11-18 08:59 UTC, Limwin94 commented on README.md
> +-  **프레젠테이션 계층(MVVM)**: 뷰 모델 (View Models) + 뷰 (Views)
```suggestion
- **데이터 레포지토리 계층** = 레포지토리 구현 부분 (Repositories Implementations) + API (네트워크) + 지속되는 DB
-  **프레젠테이션 계층(MVVM)** = 뷰 모델 (View Models) + 뷰 (Views)
```

2021-11-18 08:59 UTC, Limwin94 commented on README.md
> +해당 iOS 프로젝트는 Clean Layered Architecture와 MVVM 방식으로 구현되어있다. ("Movie"라는 아이템 이름으로 해당 템플릿이 사용되었다.) **자세한 정보는 중간 포스트에서 확인해볼 수 있다:** [Medium Post about Clean Architecture + MVVM](https://tech.olx.com/clean
**Can be used as Template project by replacing item name “Movie”**
`"Movie"라는 아이템 이름으로 해당 템플릿이 사용되었다.`가 아니라

아이템 이름인 "Movie"을 대체해서 템플릿 프로젝트로 사용할 수 있습니다. 가 맞는 것 같습니다.

2021-11-18 09:00 UTC, Limwin94 commented on README.md
> +-  **프레젠테이션 계층(MVVM)**: 뷰 모델 (View Models) + 뷰 (Views)
원문에는 `:`가 아니라 `=`로 표기되어 있습니다.

2022-04-05 08:49 UTC, closed without merging